name: flutter_blue_test
description: "Flutter Bluetooth Low Energy project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  very_good_analysis: ^5.1.0
  flutter_blue_plus: ^1.31.16
  bloc: ^8.1.3
  bloc_test: ^9.1.6
  freezed_annotation: ^2.4.1
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7

flutter:
  uses-material-design: true